package com.wayto.track.storage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEM_TABLE".
*/
public class TemTableDao extends AbstractDao<TemTable, Long> {

    public static final String TABLENAME = "TEM_TABLE";

    /**
     * Properties of entity TemTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrackId = new Property(1, long.class, "trackId", false, "TRACK_ID");
        public final static Property LocationFlag = new Property(2, int.class, "locationFlag", false, "LOCATION_FLAG");
        public final static Property TrackStatus = new Property(3, int.class, "trackStatus", false, "TRACK_STATUS");
    }


    public TemTableDao(DaoConfig config) {
        super(config);
    }
    
    public TemTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEM_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRACK_ID\" INTEGER NOT NULL ," + // 1: trackId
                "\"LOCATION_FLAG\" INTEGER NOT NULL ," + // 2: locationFlag
                "\"TRACK_STATUS\" INTEGER NOT NULL );"); // 3: trackStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEM_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TemTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTrackId());
        stmt.bindLong(3, entity.getLocationFlag());
        stmt.bindLong(4, entity.getTrackStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TemTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTrackId());
        stmt.bindLong(3, entity.getLocationFlag());
        stmt.bindLong(4, entity.getTrackStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TemTable readEntity(Cursor cursor, int offset) {
        TemTable entity = new TemTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // trackId
            cursor.getInt(offset + 2), // locationFlag
            cursor.getInt(offset + 3) // trackStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TemTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrackId(cursor.getLong(offset + 1));
        entity.setLocationFlag(cursor.getInt(offset + 2));
        entity.setTrackStatus(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TemTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TemTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TemTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
